//创建订单
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS= 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

//获取订单
export const ORDER_D_REQUEST = 'ORDER_D_REQUEST'
export const ORDER_D_SUCCESS= 'ORDER_D_SUCCESS'
export const ORDER_D_FAIL = 'ORDER_D_FAIL'

//订单支付更新
export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS= 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'